=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module OpenapiClient
  class TransactionAccount
    attr_accessor :id

    attr_accessor :name

    attr_accessor :number

    attr_accessor :current_balance

    attr_accessor :current_balance_date

    # The current balance of the transaction account in the user's base currency.
    attr_accessor :current_balance_in_base_currency

    # The exchange rate between the transaction account's currency and the user's base currency, when different. If the currencies are the same, null is returned.
    attr_accessor :current_balance_exchange_rate

    # The current safe balance, if safe balance is activated and available for the transaction account. If safe balance is not available, then null is returned.
    attr_accessor :safe_balance

    # The current safe balance in the user's base currency, if safe balance is activated and available for the transaction account. If safe balance is not available, then null is returned.
    attr_accessor :safe_balance_in_base_currency

    attr_accessor :starting_balance

    attr_accessor :starting_balance_date

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :institution

    # The currency that the account is in. This is determined by the account that the transaction account belongs to.
    attr_accessor :currency_code

    # The type of the transaction account.
    attr_accessor :type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'number' => :'number',
        :'current_balance' => :'current_balance',
        :'current_balance_date' => :'current_balance_date',
        :'current_balance_in_base_currency' => :'current_balance_in_base_currency',
        :'current_balance_exchange_rate' => :'current_balance_exchange_rate',
        :'safe_balance' => :'safe_balance',
        :'safe_balance_in_base_currency' => :'safe_balance_in_base_currency',
        :'starting_balance' => :'starting_balance',
        :'starting_balance_date' => :'starting_balance_date',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'institution' => :'institution',
        :'currency_code' => :'currency_code',
        :'type' => :'type'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'name' => :'String',
        :'number' => :'String',
        :'current_balance' => :'Float',
        :'current_balance_date' => :'String',
        :'current_balance_in_base_currency' => :'Float',
        :'current_balance_exchange_rate' => :'Float',
        :'safe_balance' => :'Float',
        :'safe_balance_in_base_currency' => :'Float',
        :'starting_balance' => :'Float',
        :'starting_balance_date' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'institution' => :'Institution',
        :'currency_code' => :'String',
        :'type' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::TransactionAccount` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::TransactionAccount`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      end

      if attributes.key?(:'current_balance')
        self.current_balance = attributes[:'current_balance']
      end

      if attributes.key?(:'current_balance_date')
        self.current_balance_date = attributes[:'current_balance_date']
      end

      if attributes.key?(:'current_balance_in_base_currency')
        self.current_balance_in_base_currency = attributes[:'current_balance_in_base_currency']
      end

      if attributes.key?(:'current_balance_exchange_rate')
        self.current_balance_exchange_rate = attributes[:'current_balance_exchange_rate']
      end

      if attributes.key?(:'safe_balance')
        self.safe_balance = attributes[:'safe_balance']
      end

      if attributes.key?(:'safe_balance_in_base_currency')
        self.safe_balance_in_base_currency = attributes[:'safe_balance_in_base_currency']
      end

      if attributes.key?(:'starting_balance')
        self.starting_balance = attributes[:'starting_balance']
      end

      if attributes.key?(:'starting_balance_date')
        self.starting_balance_date = attributes[:'starting_balance_date']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'institution')
        self.institution = attributes[:'institution']
      end

      if attributes.key?(:'currency_code')
        self.currency_code = attributes[:'currency_code']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      type_validator = EnumAttributeValidator.new('String', ["bank", "credits", "cash", "stocks", "mortgage", "loans", "vehicle", "property", "insurance", "other_asset", "other_liability"])
      return false unless type_validator.valid?(@type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["bank", "credits", "cash", "stocks", "mortgage", "loans", "vehicle", "property", "insurance", "other_asset", "other_liability"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          number == o.number &&
          current_balance == o.current_balance &&
          current_balance_date == o.current_balance_date &&
          current_balance_in_base_currency == o.current_balance_in_base_currency &&
          current_balance_exchange_rate == o.current_balance_exchange_rate &&
          safe_balance == o.safe_balance &&
          safe_balance_in_base_currency == o.safe_balance_in_base_currency &&
          starting_balance == o.starting_balance &&
          starting_balance_date == o.starting_balance_date &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          institution == o.institution &&
          currency_code == o.currency_code &&
          type == o.type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, number, current_balance, current_balance_date, current_balance_in_base_currency, current_balance_exchange_rate, safe_balance, safe_balance_in_base_currency, starting_balance, starting_balance_date, created_at, updated_at, institution, currency_code, type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
