=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module PocketsmithClient
  class Event
    # The unique identifier of the event.
    attr_accessor :id

    attr_accessor :category

    attr_accessor :scenario

    # The amount of the event.
    attr_accessor :amount

    # The amount of the event in the user's base currency.
    attr_accessor :amount_in_base_currency

    # The currency code of the event.
    attr_accessor :currency_code

    # The date of the event.
    attr_accessor :date

    # The CSS hex-style colour of the event.
    attr_accessor :colour

    # The note of the event.
    attr_accessor :note

    # The repeat type of the event.
    attr_accessor :repeat_type

    # The repeat interval of how often the event takes place.
    attr_accessor :repeat_interval

    # The unique identifier of the series that the event belongs to.
    attr_accessor :series_id

    # The unique identifier of the series followed by the series's start date.
    attr_accessor :series_start_id

    # Whether the event repeats and does not have an end date.
    attr_accessor :infinite_series

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'category' => :'category',
        :'scenario' => :'scenario',
        :'amount' => :'amount',
        :'amount_in_base_currency' => :'amount_in_base_currency',
        :'currency_code' => :'currency_code',
        :'date' => :'date',
        :'colour' => :'colour',
        :'note' => :'note',
        :'repeat_type' => :'repeat_type',
        :'repeat_interval' => :'repeat_interval',
        :'series_id' => :'series_id',
        :'series_start_id' => :'series_start_id',
        :'infinite_series' => :'infinite_series'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'category' => :'Category',
        :'scenario' => :'Scenario',
        :'amount' => :'Float',
        :'amount_in_base_currency' => :'Float',
        :'currency_code' => :'String',
        :'date' => :'String',
        :'colour' => :'String',
        :'note' => :'String',
        :'repeat_type' => :'String',
        :'repeat_interval' => :'Integer',
        :'series_id' => :'Integer',
        :'series_start_id' => :'String',
        :'infinite_series' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PocketsmithClient::Event` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PocketsmithClient::Event`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'scenario')
        self.scenario = attributes[:'scenario']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'amount_in_base_currency')
        self.amount_in_base_currency = attributes[:'amount_in_base_currency']
      end

      if attributes.key?(:'currency_code')
        self.currency_code = attributes[:'currency_code']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.key?(:'colour')
        self.colour = attributes[:'colour']
      end

      if attributes.key?(:'note')
        self.note = attributes[:'note']
      end

      if attributes.key?(:'repeat_type')
        self.repeat_type = attributes[:'repeat_type']
      end

      if attributes.key?(:'repeat_interval')
        self.repeat_interval = attributes[:'repeat_interval']
      end

      if attributes.key?(:'series_id')
        self.series_id = attributes[:'series_id']
      end

      if attributes.key?(:'series_start_id')
        self.series_start_id = attributes[:'series_start_id']
      end

      if attributes.key?(:'infinite_series')
        self.infinite_series = attributes[:'infinite_series']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      repeat_type_validator = EnumAttributeValidator.new('String', ["once", "daily", "weekly", "fortnightly", "monthly", "yearly", "each weekday"])
      return false unless repeat_type_validator.valid?(@repeat_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] repeat_type Object to be assigned
    def repeat_type=(repeat_type)
      validator = EnumAttributeValidator.new('String', ["once", "daily", "weekly", "fortnightly", "monthly", "yearly", "each weekday"])
      unless validator.valid?(repeat_type)
        fail ArgumentError, "invalid value for \"repeat_type\", must be one of #{validator.allowable_values}."
      end
      @repeat_type = repeat_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          category == o.category &&
          scenario == o.scenario &&
          amount == o.amount &&
          amount_in_base_currency == o.amount_in_base_currency &&
          currency_code == o.currency_code &&
          date == o.date &&
          colour == o.colour &&
          note == o.note &&
          repeat_type == o.repeat_type &&
          repeat_interval == o.repeat_interval &&
          series_id == o.series_id &&
          series_start_id == o.series_start_id &&
          infinite_series == o.infinite_series
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, category, scenario, amount, amount_in_base_currency, currency_code, date, colour, note, repeat_type, repeat_interval, series_id, series_start_id, infinite_series].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PocketsmithClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
