# -*- encoding: utf-8 -*-

=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "pocketsmith_ruby_client/version"

Gem::Specification.new do |s|
  s.name        = "pocketsmith_ruby_client"
  s.version     = PocketsmithRubyClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Victor Rodrigues"]
  s.email       = ["vmlrodrigues@jeunj.com"]
  s.homepage    = "https://github.com/vmlrodrigues/pocketsmith_ruby_client.git"
  s.summary     = "Pocketsmith API Ruby Gem"
  s.description = "This gem was generated from the PocketSmith OpenAPI 3 schema based at https://github.com/pocketsmith/api"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.5"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
