=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PocketsmithRubyClient::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = PocketsmithRubyClient::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(PocketsmithRubyClient::AccountsApi)
    end
  end

  # unit tests for accounts_id_delete
  # Delete account
  # Deletes an account and all its data by ID, optionally merge scenarios into another account.
  # @param id The unique identifier of the account.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'accounts_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_id_get
  # Get account
  # Gets an account by its ID.
  # @param id The unique identifier of the account.
  # @param [Hash] opts the optional parameters
  # @return [Account]
  describe 'accounts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for accounts_id_put
  # Update account
  # Updates and returns an account by its ID.
  # @param id The unique identifier of the account.
  # @param [Hash] opts the optional parameters
  # @option opts [AccountsIdPutRequest] :accounts_id_put_request 
  # @return [Account]
  describe 'accounts_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for institutions_id_accounts_get
  # List accounts in institution
  # Lists accounts belonging to an institution by its ID.
  # @param id The unique identifier of the institution.
  # @param [Hash] opts the optional parameters
  # @return [Array<Account>]
  describe 'institutions_id_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_accounts_get
  # List accounts in user
  # Lists all accounts belonging to the user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @return [Array<Account>]
  describe 'users_id_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_accounts_post
  # Create an account in user
  # Creates and returns an account belonging to the user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @option opts [UsersIdAccountsPostRequest] :users_id_accounts_post_request 
  # @return [Account]
  describe 'users_id_accounts_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_accounts_put
  # Update the display order of accounts in user
  # Updates the display order of accounts belonging to the user, by accepting an array of accounts in their new display order.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @option opts [UsersIdAccountsPutRequest] :users_id_accounts_put_request 
  # @return [Array<Account>]
  describe 'users_id_accounts_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
