=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PocketsmithRubyClient::AttachmentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AttachmentsApi' do
  before do
    # run before each test
    @api_instance = PocketsmithRubyClient::AttachmentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AttachmentsApi' do
    it 'should create an instance of AttachmentsApi' do
      expect(@api_instance).to be_instance_of(PocketsmithRubyClient::AttachmentsApi)
    end
  end

  # unit tests for attachments_id_delete
  # Delete attachment
  # Deletes a particular attachment by its ID.
  # @param id The unique identifier of the attachment.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'attachments_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for attachments_id_get
  # Get attachment
  # Gets a particular attachment by its ID.
  # @param id The unique identifier of the attachment.
  # @param [Hash] opts the optional parameters
  # @return [Attachment]
  describe 'attachments_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for attachments_id_put
  # Update attachment
  # Updates the title of the attachment.
  # @param id The unique identifier of the attachment.
  # @param [Hash] opts the optional parameters
  # @option opts [AttachmentsIdPutRequest] :attachments_id_put_request 
  # @return [Attachment]
  describe 'attachments_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_id_attachments_get
  # List attachments in transaction
  # Lists attachments belonging to a transaction by their ID.
  # @param id The unique identifier of the transaction.
  # @param [Hash] opts the optional parameters
  # @return [Array<Attachment>]
  describe 'transactions_id_attachments_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_id_attachments_post
  # Assigns attachment to transaction
  # Assigns an attachment to the transaction by their ID.
  # @param id The unique identifier of the transaction.
  # @param [Hash] opts the optional parameters
  # @option opts [TransactionsIdAttachmentsPostRequest] :transactions_id_attachments_post_request 
  # @return [Attachment]
  describe 'transactions_id_attachments_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_transaction_id_attachments_attachment_id_delete
  # Unassigns attachment in transaction
  # Unassigns a particular attachment by its ID from the transaction ID. This does not delete the attachment, it only removes its association from the transaction.
  # @param transaction_id The unique identifier of the transaction.
  # @param attachment_id The unique identifier of the attachment.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'transactions_transaction_id_attachments_attachment_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_attachments_get
  # Lists attachments in user
  # Lists attachments belonging to a user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :unassigned If set, returns unassigned attachments, that are available for assigning to a transaction.
  # @return [Array<Attachment>]
  describe 'users_id_attachments_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_attachments_post
  # Create attachment in user
  # Creates an attachment belonging to the user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @option opts [UsersIdAttachmentsPostRequest] :users_id_attachments_post_request 
  # @return [Attachment]
  describe 'users_id_attachments_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
