=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CategoriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoriesApi' do
    it 'should create an instance of CategoriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CategoriesApi)
    end
  end

  # unit tests for categories_id_delete
  # Delete category
  # Deletes a particular category by its ID. This will delete all budgets within the category, and uncategorize all transactions assigned to the category.
  # @param id The unique identifier of the category.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'categories_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for categories_id_get
  # Get category
  # Gets a particular category by its ID.
  # @param id The unique identifier of the category.
  # @param [Hash] opts the optional parameters
  # @return [Category]
  describe 'categories_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for categories_id_put
  # Update category
  # Updates a category by its ID.
  # @param id The unique identifier of the category.
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdPutRequest] :categories_id_put_request 
  # @return [Category]
  describe 'categories_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_categories_get
  # List categories in user
  # Lists all categories belonging to a user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @return [Array<Category>]
  describe 'users_id_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_categories_post
  # Create category in user
  # Creates a category belonging to the user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @option opts [UsersIdCategoriesPostRequest] :users_id_categories_post_request 
  # @return [Category]
  describe 'users_id_categories_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
