=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PocketsmithRubyClient::CategoryRulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CategoryRulesApi' do
  before do
    # run before each test
    @api_instance = PocketsmithRubyClient::CategoryRulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CategoryRulesApi' do
    it 'should create an instance of CategoryRulesApi' do
      expect(@api_instance).to be_instance_of(PocketsmithRubyClient::CategoryRulesApi)
    end
  end

  # unit tests for categories_id_category_rules_post
  # Create category rule in category
  # Creates a rule to allocate a category to transactions.
  # @param id The unique identifier of the category.
  # @param [Hash] opts the optional parameters
  # @option opts [CategoriesIdCategoryRulesPostRequest] :categories_id_category_rules_post_request 
  # @return [CategoryRule]
  describe 'categories_id_category_rules_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_category_rules_get
  # List category rules in user
  # Lists all category rules belonging to a user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @return [Array<CategoryRule>]
  describe 'users_id_category_rules_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
