=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PocketsmithRubyClient::EventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EventsApi' do
  before do
    # run before each test
    @api_instance = PocketsmithRubyClient::EventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EventsApi' do
    it 'should create an instance of EventsApi' do
      expect(@api_instance).to be_instance_of(PocketsmithRubyClient::EventsApi)
    end
  end

  # unit tests for events_id_delete
  # Delete event
  # Deletes an event by its ID.
  # @param id The unique identifier of the event.
  # @param behaviour Whether the delete applies only to this event, to all events within the series from this event or to all events within the series.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'events_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for events_id_get
  # Get event
  # Gets a particular event by its ID.
  # @param id The unique identifier of the event.
  # @param [Hash] opts the optional parameters
  # @return [Event]
  describe 'events_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for events_id_put
  # Update event
  # Updates an event by its ID.
  # @param id The unique identifier of the event.
  # @param [Hash] opts the optional parameters
  # @option opts [EventsIdPutRequest] :events_id_put_request 
  # @return [Event]
  describe 'events_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for scenarios_id_events_get
  # List events in scenario.
  # Lists events belonging to a scenario by their ID.
  # @param id The unique identifier of the scenario.
  # @param start_date Return the events from and including this date.
  # @param end_date Return the events until and including this date.
  # @param [Hash] opts the optional parameters
  # @return [Array<Event>]
  describe 'scenarios_id_events_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for scenarios_id_events_post
  # Create event in scenario
  # Creates an event in a scenario by its ID.
  # @param id The unique identifier of the scenario.
  # @param [Hash] opts the optional parameters
  # @option opts [ScenariosIdEventsPostRequest] :scenarios_id_events_post_request 
  # @return [Event]
  describe 'scenarios_id_events_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_events_get
  # List events in user.
  # Lists events belonging to a user by their ID.
  # @param id The unique identifier of the user.
  # @param start_date Return the events from and including this date.
  # @param end_date Return the events until and including this date.
  # @param [Hash] opts the optional parameters
  # @return [Array<Event>]
  describe 'users_id_events_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
