=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::InstitutionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InstitutionsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::InstitutionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstitutionsApi' do
    it 'should create an instance of InstitutionsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::InstitutionsApi)
    end
  end

  # unit tests for institutions_id_delete
  # Delete institution
  # Deletes an institution and all data within. Alternatively, another institution can be provided to merge the data into to avoid losing it.
  # @param id The unique identifier of the institution.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :merge_into_institution_id The unique identifier of the institution to merge into.
  # @return [nil]
  describe 'institutions_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for institutions_id_get
  # Get institution
  # Gets an institution by its ID.
  # @param id The unique identifier of the institution.
  # @param [Hash] opts the optional parameters
  # @return [Institution]
  describe 'institutions_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for institutions_id_put
  # Update institution
  # Updates the title and currency code for an institution.
  # @param id The unique identifier of the institution.
  # @param [Hash] opts the optional parameters
  # @option opts [InstitutionsIdPutRequest] :institutions_id_put_request 
  # @return [Institution]
  describe 'institutions_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_institutions_get
  # List institutions in user
  # Lists all the institutions belonging to the user.
  # @param id The unique identifier of the user
  # @param [Hash] opts the optional parameters
  # @return [Array<Institution>]
  describe 'users_id_institutions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_institutions_post
  # Create institution in user
  # Creates an institution belonging to a user.
  # @param id The unique identifier of the user
  # @param [Hash] opts the optional parameters
  # @option opts [UsersIdInstitutionsPostRequest] :users_id_institutions_post_request 
  # @return [Institution]
  describe 'users_id_institutions_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
