=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PocketsmithRubyClient::TimeZonesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimeZonesApi' do
  before do
    # run before each test
    @api_instance = PocketsmithRubyClient::TimeZonesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimeZonesApi' do
    it 'should create an instance of TimeZonesApi' do
      expect(@api_instance).to be_instance_of(PocketsmithRubyClient::TimeZonesApi)
    end
  end

  # unit tests for time_zones_get
  # List time zones
  # Lists time zones.
  # @param [Hash] opts the optional parameters
  # @return [Array<TimeZone>]
  describe 'time_zones_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
