=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PocketsmithRubyClient::TransactionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TransactionsApi' do
  before do
    # run before each test
    @api_instance = PocketsmithRubyClient::TransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TransactionsApi' do
    it 'should create an instance of TransactionsApi' do
      expect(@api_instance).to be_instance_of(PocketsmithRubyClient::TransactionsApi)
    end
  end

  # unit tests for accounts_id_transactions_get
  # List transactions in account
  # Lists transactions belonging to an account by its ID.
  # @param id The unique identifier of the account.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user&#39;s subscription.
  # @option opts [String] :end_date Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today&#39;s date.
  # @option opts [String] :updated_since Limit to transactions updated since an ISO 8601 timestamp.
  # @option opts [Integer] :uncategorised Limit to uncategorised transactions.
  # @option opts [String] :type Limit to transactions of this type.
  # @option opts [Integer] :needs_review Limit to transactions that need to be reviewed.
  # @option opts [String] :search Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
  # @option opts [Integer] :page Choose a particular page of the results.
  # @return [Array<Transaction>]
  describe 'accounts_id_transactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for categories_id_transactions_get
  # List transactions in categories
  # Lists transactions belonging to one or more categories by their IDs.
  # @param id A comma-separated list of category IDs.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user&#39;s subscription.
  # @option opts [String] :end_date Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today&#39;s date.
  # @option opts [String] :updated_since Limit to transactions updated since an ISO 8601 timestamp.
  # @option opts [Integer] :uncategorised Limit to uncategorised transactions.
  # @option opts [String] :type Limit to transactions of this type.
  # @option opts [Integer] :needs_review Limit to transactions that need to be reviewed.
  # @option opts [String] :search Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
  # @option opts [Integer] :page Choose a particular page of the results.
  # @return [Array<Transaction>]
  describe 'categories_id_transactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transaction_accounts_id_transactions_get
  # List transactions in transaction account
  # Lists transactions belonging to a transaction account by its ID.
  # @param id The unique identifier of the transaction account.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user&#39;s subscription.
  # @option opts [String] :end_date Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today&#39;s date.
  # @option opts [String] :updated_since Limit to transactions updated since an ISO 8601 timestamp.
  # @option opts [Integer] :uncategorised Limit to uncategorised transactions.
  # @option opts [String] :type Limit to transactions of this type.
  # @option opts [Integer] :needs_review Limit to transactions that need to be reviewed.
  # @option opts [String] :search Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
  # @option opts [Integer] :page Choose a particular page of the results.
  # @return [Array<Transaction>]
  describe 'transaction_accounts_id_transactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transaction_accounts_id_transactions_post
  # Create a transaction in transaction account
  # Creates a transaction in a transaction account by its ID.
  # @param id The unique identifier of the transaction account.
  # @param [Hash] opts the optional parameters
  # @option opts [TransactionAccountsIdTransactionsPostRequest] :transaction_accounts_id_transactions_post_request 
  # @return [Transaction]
  describe 'transaction_accounts_id_transactions_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_id_delete
  # Delete transaction
  # Deletes a transaction and all its data by ID.
  # @param id The unique identifier of the transaction.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'transactions_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_id_get
  # Get a transaction
  # Gets a transaction by its ID.
  # @param id The unique identifier of the transaction.
  # @param [Hash] opts the optional parameters
  # @return [Transaction]
  describe 'transactions_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for transactions_id_put
  # Update a transaction
  # Updates a transaction by its ID.
  # @param id The unique identifier of the transaction.
  # @param [Hash] opts the optional parameters
  # @option opts [TransactionsIdPutRequest] :transactions_id_put_request 
  # @return [Transaction]
  describe 'transactions_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for users_id_transactions_get
  # List transactions in user
  # Lists transactions belonging to a user by their ID.
  # @param id The unique identifier of the user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_date Limit to transactions on or after this date. Required if end_date is provided. If not provided, defaults to the furtherest date allowed by the user&#39;s subscription.
  # @option opts [String] :end_date Limit to transactions on or before this date. Required if start_date is provided. If not provided, defaults to today&#39;s date.
  # @option opts [String] :updated_since Limit to transactions updated since an ISO 8601 timestamp.
  # @option opts [Integer] :uncategorised Limit to uncategorised transactions.
  # @option opts [String] :type Limit to transactions of this type.
  # @option opts [Integer] :needs_review Limit to transactions that need to be reviewed.
  # @option opts [String] :search Limit to transactions matching a keyword search string. The provided string is matched against the transaction amount, account name, payee, category title, note, labels, and the date in ISO 8601 format.
  # @option opts [Integer] :page Choose a particular page of the results.
  # @return [Array<Transaction>]
  describe 'users_id_transactions_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
