=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PocketsmithClient::AttachmentVariants
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PocketsmithClient::AttachmentVariants do
  let(:instance) { PocketsmithClient::AttachmentVariants.new }

  describe 'test an instance of AttachmentVariants' do
    it 'should create an instance of AttachmentVariants' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PocketsmithClient::AttachmentVariants)
    end
  end

  describe 'test attribute "large_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "thumb_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
