=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PocketsmithRubyClient::InstitutionsIdPutRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PocketsmithRubyClient::InstitutionsIdPutRequest do
  let(:instance) { PocketsmithRubyClient::InstitutionsIdPutRequest.new }

  describe 'test an instance of InstitutionsIdPutRequest' do
    it 'should create an instance of InstitutionsIdPutRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PocketsmithRubyClient::InstitutionsIdPutRequest)
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "currency_code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
