=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TransactionAccountsIdPutRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TransactionAccountsIdPutRequest do
  let(:instance) { OpenapiClient::TransactionAccountsIdPutRequest.new }

  describe 'test an instance of TransactionAccountsIdPutRequest' do
    it 'should create an instance of TransactionAccountsIdPutRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::TransactionAccountsIdPutRequest)
    end
  end

  describe 'test attribute "institution_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "starting_balance"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "starting_balance_date"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
