=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PocketsmithRubyClient::TransactionsIdAttachmentsPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PocketsmithRubyClient::TransactionsIdAttachmentsPostRequest do
  let(:instance) { PocketsmithRubyClient::TransactionsIdAttachmentsPostRequest.new }

  describe 'test an instance of TransactionsIdAttachmentsPostRequest' do
    it 'should create an instance of TransactionsIdAttachmentsPostRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PocketsmithRubyClient::TransactionsIdAttachmentsPostRequest)
    end
  end

  describe 'test attribute "attachment_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
