=begin
#PocketSmith

#The PocketSmith API

The version of the OpenAPI document: 2.0
Contact: api@pocketsmith.com
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account'
require 'openapi_client/models/accounts_id_put_request'
require 'openapi_client/models/attachment'
require 'openapi_client/models/attachment_content_type_meta'
require 'openapi_client/models/attachment_variants'
require 'openapi_client/models/attachments_id_put_request'
require 'openapi_client/models/budget_analysis'
require 'openapi_client/models/budget_analysis_package'
require 'openapi_client/models/categories_id_category_rules_post_request'
require 'openapi_client/models/categories_id_put_request'
require 'openapi_client/models/category'
require 'openapi_client/models/category_rule'
require 'openapi_client/models/currency'
require 'openapi_client/models/currency_separators'
require 'openapi_client/models/error'
require 'openapi_client/models/event'
require 'openapi_client/models/events_id_put_request'
require 'openapi_client/models/institution'
require 'openapi_client/models/institutions_id_put_request'
require 'openapi_client/models/period'
require 'openapi_client/models/saved_search'
require 'openapi_client/models/scenario'
require 'openapi_client/models/scenarios_id_events_post_request'
require 'openapi_client/models/time_zone'
require 'openapi_client/models/transaction'
require 'openapi_client/models/transaction_account'
require 'openapi_client/models/transaction_accounts_id_put_request'
require 'openapi_client/models/transaction_accounts_id_transactions_post_request'
require 'openapi_client/models/transactions_id_attachments_post_request'
require 'openapi_client/models/transactions_id_put_request'
require 'openapi_client/models/user'
require 'openapi_client/models/users_id_accounts_post_request'
require 'openapi_client/models/users_id_accounts_put_request'
require 'openapi_client/models/users_id_attachments_post_request'
require 'openapi_client/models/users_id_categories_post_request'
require 'openapi_client/models/users_id_institutions_post_request'
require 'openapi_client/models/users_id_put_request'

# APIs
require 'openapi_client/api/accounts_api'
require 'openapi_client/api/attachments_api'
require 'openapi_client/api/budgeting_api'
require 'openapi_client/api/categories_api'
require 'openapi_client/api/category_rules_api'
require 'openapi_client/api/currencies_api'
require 'openapi_client/api/events_api'
require 'openapi_client/api/institutions_api'
require 'openapi_client/api/labels_api'
require 'openapi_client/api/saved_searches_api'
require 'openapi_client/api/time_zones_api'
require 'openapi_client/api/transaction_accounts_api'
require 'openapi_client/api/transactions_api'
require 'openapi_client/api/users_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
